Fix typos
neonbjb/tortoise-tts pull request #233
Opened 2023-01-05 11:50 UTC by kianmeng

Found via `codespell -S *.json -L splitted,nd,ser`

2023-01-05 23:31 UTC, neonbjb requested changes

2023-01-05 23:31 UTC, neonbjb commented on tortoise/models/transformer.py
> +from rotary_embedding_torch import RotaryEmbedding, broadcast
This is unfortunately not my typo. :(

2023-01-06 09:05 UTC, neonbjb approved these changes

2023-01-16 17:37 UTC, TheDummie450 approved these changes

2023-01-18 01:24 UTC, merged

2023-01-18 03:48 UTC, kianmeng commented
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face: